# Site Settings
name: Revista A-Sol
title: A-Sol | Revista Digital
description: Revista digital produzida mensalmente pelo Cursinho Comunitário A-Sol.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: adm.asol@outlook.com
show_hero: true
menu:
  - title: Home
    url: /
  - title: Sobre
    url: /sobre
  - title: Contato
    url: /contato
  - title: Feed
    url: /feed.xml


# Social Media Settings
# Remove the item if you don't need it
facebook_username: cursinhoasol
instagram_username: cursinhoa.sol


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "/revista" # the subpath of your site, e.g. /blog
url: "http://cursinhoasol.com.br/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version:
